spring:
  datasource:
    url: "jdbc:mysql://localhost/thalestest"
    username: "user"
    password: "user"
    driver-class-name: "com.mysql.cj.jdbc.Driver"

  jpa:
    properties:
      hibernate:
          show-sql: true
          ddl-auto: update
    database: mysql
  main:
    allow-bean-definition-overriding: on
